name: first_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  dio: ^5.6.0
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.2

dev_dependencies: 
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true